// Gateway model catalog: maps the endpoint ids the studios post
// (`POST /api/v1/<key>`) to fal.ai endpoints and turns studio payloads into
// fal inputs. The data lives in catalog.json, generated by
// `node scripts/build-gateway-catalog.mjs` from ./sources — edit the sources
// (usually sources/overrides.json) and rebuild; never hand-edit catalog.json.
//
// Server-only: nothing here reads secrets, but the catalog is an allowlist and
// must be enforced on the server.

import catalog from './catalog.json';
import { applyTransforms, isBlank, matchesWhen, parseNumeric, snapToEnum } from './transforms.js';

const PRICING = Object.freeze({
    t2i: { usd: 0.04, per: 'image' },
    i2i: { usd: 0.04, per: 'image' },
    t2v: { usd: 0.4, per: '5s' },
    i2v: { usd: 0.4, per: '5s' },
    v2v: { usd: 0.5, per: 'call' },
    lipsync: { usd: 0.3, per: 'call' },
    audio: { usd: 0.05, per: 'call' },
    tool: { usd: 0.02, per: 'call' },
});

const URL_FIELD_RE = /(^|_)urls?$/i;
const SCHEME_URL_RE = /^\s*([a-z][a-z0-9+.-]*):\/\//i;
const RISKY_SCHEME_RE = /^\s*(data|file|javascript|vbscript|blob|about|ftp|gopher|ws|wss|chrome|view-source|jar|ldap|dict|smb|tftp):/i;
const MAX_ARRAY_ITEMS = 50;

function deepFreeze(value) {
    if (value && typeof value === 'object' && !Object.isFrozen(value)) {
        Object.freeze(value);
        for (const child of Object.values(value)) deepFreeze(child);
    }
    return value;
}

const ENTRIES = deepFreeze(Array.isArray(catalog?.entries) ? catalog.entries : []);
const BY_KEY = new Map(ENTRIES.map((entry) => [entry.key, entry]));

function hasOwn(object, key) {
    return object !== null && typeof object === 'object' && Object.prototype.hasOwnProperty.call(object, key);
}

const UNSAFE_KEYS = new Set(['__proto__', 'constructor', 'prototype']);

// Deep copy of JSON-ish data that never carries prototype-changing keys.
function clone(value, depth = 0) {
    if (depth > 8) return undefined;
    if (Array.isArray(value)) return value.map((item) => clone(item, depth + 1));
    if (value && typeof value === 'object') {
        const copy = {};
        for (const [key, child] of Object.entries(value)) {
            if (!UNSAFE_KEYS.has(key)) copy[key] = clone(child, depth + 1);
        }
        return copy;
    }
    return value;
}

function inputError(field, message, code = 'invalid_input') {
    const error = new Error(message);
    error.status = 400;
    error.code = code;
    error.field = field;
    error.expose = true;
    error.body = { error: code, field, message };
    return error;
}

/** Catalog entry for a studio endpoint key, or null. */
export function getEntry(key) {
    if (typeof key !== 'string') return null;
    return BY_KEY.get(key) || null;
}

/**
 * Public-safe model availability for the studio pickers: endpoint keys, plus
 * `disabled_models` — studio model ids that post an enabled key but whose own
 * presets fal cannot serve (hide those models too).
 */
export function listAvailable() {
    const enabled = [];
    const disabled = [];
    const disabledModels = [];
    for (const entry of ENTRIES) {
        (entry.enabled ? enabled : disabled).push(entry.key);
        if (entry.enabled) disabledModels.push(...(entry.unsupported_models || []));
    }
    return { enabled, disabled, disabled_models: disabledModels };
}

/**
 * All catalog entries (frozen), optionally filtered — for workflows/agents.
 * @param {{enabled?: boolean, kind?: string, list?: string, category?: string}} [filter]
 */
export function listEntries(filter = {}) {
    return ENTRIES.filter((entry) => {
        if (typeof filter.enabled === 'boolean' && entry.enabled !== filter.enabled) return false;
        if (filter.kind && entry.kind !== filter.kind) return false;
        if (filter.category && entry.category !== filter.category) return false;
        if (filter.list && !(entry.lists || [entry.list]).includes(filter.list)) return false;
        return true;
    });
}

function pickVariant(entry, payload) {
    for (const variant of entry.variants || []) {
        if (matchesWhen(variant.when, payload)) return variant;
    }
    return { fal: entry.fal, input: entry.input };
}

function studioField(spec, falField) {
    for (const [source, target] of Object.entries(spec.rename || {})) {
        if (target === falField) return source;
    }
    for (const step of spec.transforms || []) {
        if (step.field === falField && typeof step.from === 'string') return step.from;
    }
    return falField;
}

function checkUrlString(value, field, urlField) {
    const text = value.trim();
    const scheme = SCHEME_URL_RE.exec(text);
    if (scheme && !/^https?$/i.test(scheme[1])) {
        throw inputError(field, `${field} must be an http(s) URL`);
    }
    if (urlField || scheme) {
        if (RISKY_SCHEME_RE.test(text) || !/^https?:\/\//i.test(text)) {
            throw inputError(field, `${field} must be an http(s) URL`);
        }
        let parsed;
        try {
            parsed = new URL(text);
        } catch {
            throw inputError(field, `${field} is not a valid URL`);
        }
        if (!parsed.hostname || parsed.username || parsed.password) {
            throw inputError(field, `${field} is not a valid URL`);
        }
    }
}

function assertSafeUrls(value, field, urlField) {
    if (typeof value === 'string') {
        checkUrlString(value, field, urlField);
    } else if (Array.isArray(value)) {
        for (const item of value) assertSafeUrls(item, field, urlField);
    } else if (value && typeof value === 'object') {
        for (const [key, child] of Object.entries(value)) {
            assertSafeUrls(child, field, urlField || URL_FIELD_RE.test(key) || key === 'path' && typeof child === 'string' && SCHEME_URL_RE.test(child));
        }
    }
}

function coerceScalar(value, type) {
    const types = String(type || 'any').split('|');
    if (types.includes('any')) return value;
    if (typeof value === 'string') {
        if (types.includes('string')) return value;
        if (types.includes('integer') || types.includes('number')) {
            // '8', '8s', '8.5' → number (units are dropped: the enum snap handles them).
            const parsed = parseNumeric(value);
            if (!parsed) return undefined;
            return types.includes('integer') ? Math.round(parsed.n) : parsed.n;
        }
        if (types.includes('boolean')) {
            const text = value.trim().toLowerCase();
            if (text === 'true') return true;
            if (text === 'false') return false;
            return undefined;
        }
        return types.includes('object') ? undefined : value;
    }
    if (typeof value === 'number') {
        if (types.includes('integer')) return Math.round(value);
        if (types.includes('number')) return value;
        if (types.includes('string')) return String(value);
        if (types.includes('boolean')) return value !== 0;
        return undefined;
    }
    if (typeof value === 'boolean') {
        if (types.includes('boolean')) return value;
        if (types.includes('string')) return String(value);
        return undefined;
    }
    if (value && typeof value === 'object') {
        return types.includes('object') ? value : undefined;
    }
    return value;
}

function coerceField(name, value, spec, label) {
    const type = spec.types?.[name] || 'any';
    const types = type.split('|');
    const enumValues = spec.enums?.[name];
    const range = spec.ranges?.[name];

    if (types.includes('array')) {
        let list = Array.isArray(value) ? value : [value];
        const itemSpec = spec.items?.[name] || {};
        list = list.filter((item) => !isBlank(item)).map((item) => {
            const coerced = coerceScalar(item, itemSpec.type || 'any');
            if (coerced === undefined) throw inputError(label, `${label} has an invalid item`);
            if (itemSpec.enum && (typeof coerced === 'string' || typeof coerced === 'number')) {
                const snapped = snapToEnum(coerced, itemSpec.enum);
                if (snapped === undefined) throw inputError(label, `${label} has an unsupported item: ${String(coerced).slice(0, 60)}`);
                return snapped;
            }
            return coerced;
        });
        const maxItems = Math.min(Number.isFinite(itemSpec.max_items) ? itemSpec.max_items : MAX_ARRAY_ITEMS, MAX_ARRAY_ITEMS);
        return list.slice(0, maxItems);
    }

    let current = value;
    if (Array.isArray(current)) {
        // A list sent to a scalar field (e.g. images_list → image_url).
        current = current.find((item) => !isBlank(item));
        if (current === undefined) return undefined;
    }
    const coerced = coerceScalar(current, type);
    if (coerced === undefined) {
        throw inputError(label, `${label} has an unsupported value`);
    }
    current = coerced;

    if (enumValues && (typeof current === 'string' || typeof current === 'number')) {
        const snapped = snapToEnum(current, enumValues);
        if (snapped === undefined) {
            // image_size-style unions accept either a preset or {width,height}.
            throw inputError(label, `${label} does not support "${String(current).slice(0, 60)}"`);
        }
        current = snapped;
    }

    if (range && typeof current === 'number') {
        const [low, high] = range;
        if (Number.isFinite(low)) current = Math.max(low, current);
        if (Number.isFinite(high)) current = Math.min(high, current);
    }
    if (current && typeof current === 'object' && !Array.isArray(current) && types.includes('object')) {
        for (const side of ['width', 'height']) {
            if (hasOwn(current, side)) {
                const number = Number(current[side]);
                if (!Number.isFinite(number) || number <= 0) throw inputError(label, `${label}.${side} must be a positive number`);
                current = { ...current, [side]: Math.round(number) };
            }
        }
    }
    return current;
}

/**
 * Translate a studio payload into the fal input for this entry.
 * rename → transforms → fixed → keep allowed → validate/coerce.
 * @returns {{input: object, endpoint: string}} endpoint is the fal endpoint
 *   id to submit to (a variant may route to a sibling endpoint).
 * @throws Error with .status=400, .field, .code='invalid_input'
 */
export function buildFalInput(entry, payload = {}) {
    if (!entry || typeof entry !== 'object' || !entry.key) {
        throw inputError('model', 'Unknown model', 'unknown_model');
    }
    if (!entry.enabled) {
        throw inputError('model', 'This model is not available right now', 'model_unavailable');
    }
    if (payload === null || typeof payload !== 'object' || Array.isArray(payload)) {
        throw inputError('payload', 'Request body must be a JSON object');
    }

    const variant = pickVariant(entry, payload);
    const spec = variant.input || {};
    const dropped = new Set(spec.drop || []);

    const work = {};
    for (const [key, value] of Object.entries(payload)) {
        if (key === 'model' || key.startsWith('_') || UNSAFE_KEYS.has(key) || dropped.has(key)) continue;
        if (isBlank(value) || (Array.isArray(value) && value.every(isBlank))) continue;
        work[key] = clone(value);
    }

    // Renames read from the untouched payload copy so swaps and fan-in work;
    // the first non-blank source wins when several map to one fal field.
    const renamed = { ...work };
    const assigned = new Set();
    for (const [source, target] of Object.entries(spec.rename || {})) {
        if (!hasOwn(work, source)) continue;
        if (source !== target) delete renamed[source];
        if (assigned.has(target)) continue;
        renamed[target] = work[source];
        assigned.add(target);
    }

    applyTransforms(spec.transforms, renamed, spec);

    for (const [key, value] of Object.entries(spec.fixed || {})) {
        renamed[key] = clone(value);
    }

    const allowed = new Set(spec.allowed || []);
    const input = {};
    for (const [key, value] of Object.entries(renamed)) {
        if (!allowed.has(key)) continue;
        if (isBlank(value)) continue;
        const label = studioField(spec, key);
        const coerced = coerceField(key, value, spec, label);
        if (coerced === undefined || (Array.isArray(coerced) && coerced.length === 0)) continue;
        assertSafeUrls(coerced, label, URL_FIELD_RE.test(key));
        input[key] = coerced;
    }

    for (const field of spec.required || []) {
        const value = input[field];
        if (isBlank(value) || (Array.isArray(value) && value.length === 0)) {
            const label = studioField(spec, field);
            throw inputError(label, `${label} is required`);
        }
    }

    return { input, endpoint: variant.fal || entry.fal };
}

/* ─────────────────────────── outputs ─────────────────────────── */

function isHttpUrl(value) {
    return typeof value === 'string' && /^https?:\/\//i.test(value.trim());
}

function fileOf(value) {
    if (isHttpUrl(value)) return { url: value.trim() };
    if (value && typeof value === 'object' && isHttpUrl(value.url)) {
        const file = { url: value.url.trim() };
        for (const key of ['width', 'height', 'content_type', 'file_name', 'file_size']) {
            if (value[key] !== undefined && value[key] !== null) file[key] = value[key];
        }
        return file;
    }
    return null;
}

function filesAt(root, path) {
    if (!root || typeof root !== 'object' || typeof path !== 'string') return [];
    const clean = path.split(/\s/)[0];
    const match = /^([A-Za-z0-9_.]+?)(\[\])?(?:\.url)?$/.exec(clean);
    if (!match) return [];
    let node = root;
    for (const key of match[1].split('.')) {
        if (!node || typeof node !== 'object') return [];
        node = node[key];
    }
    const list = Array.isArray(node) ? node : [node];
    return list.map(fileOf).filter(Boolean);
}

const FALLBACK_PATHS = [
    ['images[].url', 'image'],
    ['image.url', 'image'],
    ['video.url', 'video'],
    ['videos[].url', 'video'],
    ['audio.url', 'audio'],
    ['audio_file.url', 'audio'],
    ['audio_url', 'audio'],
    ['model_mesh.url', 'model'],
    ['output.images[].url', 'image'],
    ['output.image.url', 'image'],
    ['output.video.url', 'video'],
    ['output.audio.url', 'audio'],
    ['output.url', 'file'],
    ['file.url', 'file'],
    ['url', 'file'],
    ['outputs[]', 'file'],
];

function kindOfPath(path) {
    if (/^(output\.)?images?\b/.test(path)) return 'image';
    if (/^(output\.)?videos?\b/.test(path)) return 'video';
    if (/^(output\.)?audio/.test(path)) return 'audio';
    return 'file';
}

/**
 * Pull media URLs out of a fal result. Uses the declared output path (of the
 * variant that served `endpoint`, when given) first, then generic fallbacks.
 * Only http(s) URLs are returned.
 * @returns {{urls: string[], kind: string, images: object[], video: object|null, audio: object|null}}
 */
export function extractOutputs(entry, falOutput, endpoint) {
    const root = falOutput && typeof falOutput === 'object' ? falOutput : {};
    let files = [];
    let kind = 'file';
    const variant = endpoint ? (entry?.variants || []).find((candidate) => candidate.fal === endpoint) : null;
    const declaredPath = variant?.output || entry?.output;
    const declared = typeof declaredPath === 'string' ? declaredPath : null;
    if (declared) {
        files = filesAt(root, declared);
        kind = kindOfPath(declared);
    }
    if (files.length === 0) {
        for (const [path, pathKind] of FALLBACK_PATHS) {
            files = filesAt(root, path);
            if (files.length > 0) { kind = pathKind; break; }
        }
    }
    if (kind === 'file' && entry?.output_kind) kind = entry.output_kind;
    const seen = new Set();
    files = files.filter((file) => (seen.has(file.url) ? false : seen.add(file.url)));
    return {
        urls: files.map((file) => file.url),
        kind,
        images: kind === 'image' ? files : [],
        video: kind === 'video' ? files[0] || null : null,
        audio: kind === 'audio' ? files[0] || null : null,
    };
}

/* ─────────────────────────── pricing ─────────────────────────── */

function secondsOf(value) {
    const parsed = parseNumeric(value);
    if (!parsed || !(parsed.n > 0)) return null;
    return parsed.n;
}

/**
 * Static spend estimate (USD) for a submit, from SPEC §2 category defaults,
 * scaled by duration (video) or image count. When the payload builds, the
 * values fal will actually receive are used (a fixed 8s clip, a clamped image
 * count), so the budget is not charged for settings the model ignores.
 * pricing.js may refine it with live fal pricing.
 */
export function estimateUsd(entry, payload = {}) {
    if (!entry) return 0;
    const pricing = entry.pricing || PRICING[entry.category] || PRICING.tool;
    const usd = Number(pricing.usd) || 0;
    const body = payload && typeof payload === 'object' && !Array.isArray(payload) ? payload : {};
    let built = null;
    if (entry.enabled && pricing.per !== 'call') {
        try {
            built = buildFalInput(entry, body).input;
        } catch {
            built = null;
        }
    }
    let units = 1;
    if (pricing.per === '5s') {
        // num_frames without an fps: fal's video models default to ~24 fps.
        const framesSeconds = built && Number(built.num_frames) > 0
            ? Number(built.num_frames) / (Number(built.fps || built.frames_per_second) > 0 ? Number(built.fps || built.frames_per_second) : 24)
            : null;
        const builtSeconds = secondsOf(built?.duration);
        const seconds = (builtSeconds !== null || framesSeconds !== null ? Math.max(builtSeconds || 0, framesSeconds || 0) : null) ?? secondsOf(body.duration)
            ?? secondsOf(body.duration_seconds) ?? secondsOf(entry.defaults?.duration) ?? 5;
        units = Math.min(Math.max(seconds, 1), 120) / 5;
    } else if (pricing.per === 'image') {
        const count = built
            ? secondsOf(built.num_images) ?? secondsOf(built.max_images) ?? 1
            : secondsOf(body.num_images) ?? secondsOf(body.batch_size) ?? secondsOf(entry.defaults?.num_images) ?? 1;
        units = Math.min(Math.max(Math.round(count), 1), 16);
    }
    return Math.round(usd * units * 10000) / 10000;
}
